version: '3'

services:
  web:
    container_name: dev-blog_nginx
    image: nginx:latest
    volumes:
      - './.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './src/:/var/src/html'
    ports:
      - '80:80'
    depends_on:
      - php
      - db
  php:
    container_name: dev-blog_php
    build: .docker/php
    user: '${UID}:${GID}'
    volumes:
      - './.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini'
      - './.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini'
      - './src/:/var/src/html'
  composer:
    container_name: dev-blog_composer
    image: composer
    user: '${UID}:${GID}'
    volumes:
      - './src/:/app'
    command: install
  db:
    container_name: dev-blog_db
    image: 'postgres:10.12'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    ports:
      - '5432:5432'
    volumes:
      - './.docker/postgres/data:/var/lib/postgresql/data'
      - './.docker/postgres:/docker-entrypoint-initdb.d'